### ISSUE TITLE
Feature: Regularly saving of RFE-files

### ISSUE THREAD

**Issue by mircojung** [RFExplorer/RFExplorer-for-Windows#1]
Hello Team!
Can you implement a autosave-function, please?

e.g. file-menue -> checkboxed '5 minute autosave to file'

Thanks for your Software, nicely done!
Mirco

**Comment by arocholl** [comment]
Hi Mirco, thanks for your suggestion, we will add it to the queue.

**Comment by arocholl** [comment]
Assigned as task RFE T0063

**Comment by mballesteros-IEEE** [comment]
Changed to task RFE T0070

**Comment by mballesteros-IEEE** [comment]
Hi Mirco,

RF Explorer for Windows version 1.17.1710.3 with autosave function is available in our webpage: 
[www.rf-explorer.com/download](www.rf-explorer.com/download)

More information available on this feature in Release Notes included with the software

If you have other comments don't hesitate to contact us.

Best Regards

Manuel Ballesteros
